source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '0.2.11'
gem 'oauth'
gem 'oauth-plugin'
gem 'oauth2'
gem 'twitter', '4.1.0'
gem "delayed_job"
gem 'will_paginate'
gem 'jquery-rails'
gem 'authlogic'
gem 'capistrano'
gem 'rvm'
gem 'rvm-capistrano'
gem 'delayed_job_active_record'
gem 'thin'

group :test, :cucumber do
  gem 'factory_girl_rails'
  gem 'rspec'
  gem 'rcov','0.9.9'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'gherkin'
  gem 'rspec-rails'
  gem 'spork'
  gem 'launchy'
  gem 'rack-test'
  gem 'mongrel', '1.2.0.pre2'
end